### ISSUE TITLE
ETAG not checking for changes in HEADERs

### ISSUE THREAD

**Issue by mxaddict** [matthewbdaly/laravel-etag-middleware#12]
Is it possible to check for changes in the $response HEADERs as well?

I've run into an issue where I have a CORS middleware that returns dynamic "Access-Control-*" depending on the "Origin" header value, which get's ignore because ETAG for the reponse BODY is the same as a request from another site that got a different CORS response.

Ideally the ETAG should be different if laravel response HEADERs are different.

https://github.com/matthewbdaly/laravel-etag-middleware/blob/8e83a34e700edf978c576fc469ba204209188173/src/ETag.php#L33

**Comment by mxaddict** [comment]
Let me know if you're interested in a PR for this. Or give me your thoughts on why it should not be done.

**Comment by matthewbdaly** [comment]
Yes, that makes sense.

If you want to submit a pull request for that I'll take a look at it.

**Comment by mxaddict** [comment]
Ok, I'll see what I can come up with.
