### ISSUE TITLE
[Buzzkill] Laravel 5.6+ has a SetCacheHeaders middleware.

### ISSUE THREAD

**Issue by jpickwell** [matthewbdaly/laravel-etag-middleware#19]
Laravel 5.6+ has a SetCacheHeaders middleware which supports Symfony's "etag" option of `Response@setCache`. (https://github.com/laravel/framework/blob/5.6/src/Illuminate/Http/Middleware/SetCacheHeaders.php)

Laravel 6.4+ also supports the "last_modified" option. (https://github.com/laravel/framework/blob/v6.4.0/src/Illuminate/Http/Middleware/SetCacheHeaders.php)

**Comment by matthewbdaly** [comment]
To be honest, I can still see a use case for this package in terms of simplicity, since this requires more configuration, but it's good to know this alternative exists.
